---
- name : working on tomcat containers
  hosts : all
  tasks :  
     - name : start tomcat as a container
       docker_container :
                image : tomcat
                name : mytomcat
     - name : stop container
       docker_container :
                name : mytomcat
                state : stopped
     - name : remove container
       docker_container :
                name : mytomcat
                state : absent
...

