---
- name: error handling
  hosts: all
  tasks:
   - block: 
      - name: apache1
        apt:
         name : apache1
         state: present
     rescue:
      - name: install apache2
        apt:
         name: apache2
         state: present
     always:
      - name: install tomcat8
        apt: 
         name: tomcat8
         state: present
...

