---
 - name : install & uninstall s/w
   hosts : all
   tasks :
    - name : install s/w
      apt :
       name : "{{item.a}}"
       state : "{{item.b}}"
       update_cache : "{{item.c}}"
      with_items : 
       - {a: tree,b: present,c: no}
       - {a: git,b: present,c: no}
       - {a: tomcat8,b: present,c: yes}
...
