---
- name : create 10 nginx containers
  hosts : all
  tasks : 
    - name : Create 10 nginx
      docker_container :
             image : nginx
             name : "Container{{item}}"
      with_sequence : count=10
...
