---
 - name : install firewalld using group variables
   hosts : webserver
   tasks :
     - name : install firewalld
       apt :
        name : "{{a}}"
        state : "{{b}}"
        update_cache : "{{c}}"
...
