---
- name : download docker images
  hosts: all
  tasks:
    - name: pull docker images
      docker_image: 
         name: "{{item}}"
      with_items:
         - httpd
         - tomcat
         - postgres
...

