- name: configure apache2 using handlers
  hosts: all
  tasks:
    - name: apache2 install
      apt:
       name: apache2
       state: present
       update_cache: yes
      notify: 
       - Check url response
    - name: Edit the index.html
      copy: 
       content: "welcome to intelliq\n"
       dest: /var/www/html/index.html
      notify:
       - Restart apache2
  handlers:
    - name: Restart apache2
      service:
       name: apache2
       state: restarted
    - name: Check url response
      uri:
       url: "{{item}}"
       status: 200
      with_items:
       - http://172.31.31.128
       - http://172.31.31.166
...
