---
- name: start mysql as container and link wordpress container
  hosts: all
  tasks: 
     - name : start mysql container
       docker_container:
               image: mysql:5
               name: mydb
               env:
                 MYSQL_ROOT_PASSWORD: Intelliq
     - name : start wordpress container
       docker_container:
               image: wordpress
               name: mywordpress
               ports:
                 "7070:80"
               links:
                - "mydb:mysql"
...
